name: Daruma CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Linter
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Run Tests and Generate Coverage
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.organization=darumashop
            -Dsonar.projectKey=DarumaShop_daruma-platform
            -Dsonar.sources=apps/backend/src
            -Dsonar.tests=apps/backend/test
            -Dsonar.javascript.lcov.reportPaths=apps/backend/coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
